spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: usernameaqui
    password: senhaaqui
    protocol: smtp
    properties:
      mail:
          smtp:
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
              fallback: false
            auth: true
            starttls:
              enable: true
            connectionTimeout: 5000
            timeout: 3000
            writeTimeout: 5000
      thymeleaf:
        enable: true

    send:
      email:
        from: usernameaqui
        name: 'Agendador de Tarefas'

    server:
      port: 8082